# Generated by Django 4.2.4 on 2023-08-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name_plural": "Inbox"},
        ),
        migrations.AlterField(
            model_name="customer",
            name="file",
            field=models.FileField(default=False, upload_to=""),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Read", "Read")],
                default="Pending",
                max_length=15,
            ),
        ),
    ]
